START TRANSACTION;
ALTER TABLE "Orders" DROP CONSTRAINT "FK_Orders_Users_UserId";

ALTER TABLE "Users" DROP CONSTRAINT "PK_Users";

ALTER TABLE "Users" DROP COLUMN "Password";

ALTER TABLE "Users" RENAME TO "AspNetUsers";

ALTER TABLE "AspNetUsers" RENAME COLUMN "EMail" TO "Email";

ALTER TABLE "AspNetUsers" RENAME COLUMN "Code" TO "AccessFailedCount";

ALTER TABLE "Orders" ALTER COLUMN "UserId" TYPE text;

ALTER TABLE "AspNetUsers" ALTER COLUMN "Email" TYPE character varying(256);

ALTER TABLE "AspNetUsers" ALTER COLUMN "Id" TYPE text;
ALTER TABLE "AspNetUsers" ALTER COLUMN "Id" DROP IDENTITY;

ALTER TABLE "AspNetUsers" ADD "ConcurrencyStamp" text;

ALTER TABLE "AspNetUsers" ADD "EmailConfirmed" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "AspNetUsers" ADD "LockoutEnabled" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "AspNetUsers" ADD "LockoutEnd" timestamp with time zone;

ALTER TABLE "AspNetUsers" ADD "NormalizedEmail" character varying(256);

ALTER TABLE "AspNetUsers" ADD "NormalizedUserName" character varying(256);

ALTER TABLE "AspNetUsers" ADD "PasswordHash" text;

ALTER TABLE "AspNetUsers" ADD "PhoneNumberConfirmed" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "AspNetUsers" ADD "SecurityStamp" text;

ALTER TABLE "AspNetUsers" ADD "TwoFactorEnabled" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "AspNetUsers" ADD "UserName" character varying(256);

ALTER TABLE "AspNetUsers" ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250911061158_test', '9.0.9');

COMMIT;

